### PR TITLE
Update the Ubuntu version for build and tests.

### PR DESCRIPTION
**Pull request by tcsnfkx**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/30)

**Review by wliue — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @Marco-Premier, @stevenwarejones, and @wangyaopw)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @stevenwarejones, and @wangyaopw)

**Review by wangyaopw — APPROVED** [review]

**Review by wangyaopw — APPROVED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv and @stevenwarejones)

**Pull request merged**
