### PR TITLE
Create a binary to perform sanity checks on a VID model.

### LINKED ISSUE #14: Create a binary to do sanity check on virtual people model

### PR DESCRIPTION
**Pull request by tcsnfkx**
The model is stored in a Riegeli file as a list of CompiledNodes.
Currently will check if there is any duplicated node names among all the
nodes, and for each node if there is any duplicated seeds among the
nodes on the path from root to that node.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_names_checker.cc, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Mr4L29C6rnHRo9rkfG6:-Mr4L29C6rnHRo9rkfG7:b53e8ab) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/0eafae3815c866156d6d72c7cb2766e260fb9373/src/main/cc/wfa/virtual_people/training/model_checker/model_names_checker.cc#L35)):*
> ```cpp
>           absl::StrCat("Duplicated node names: ", name));
>     }
>     names.emplace(node.name());
> ```

Preferred:

```
auto [it, inserted] = names.insert(node.name());
if (!inserted) { return absl::InvalidArgumentError(...); }
```

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12)* status: all files reviewed, 6 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Mr4PLnn4L_f0-aZgPzl:-Mr4PLnn4L_f0-aZgPzm:bhnz99h) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/0eafae3815c866156d6d72c7cb2766e260fb9373/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L44)):*
> ```cpp
>   absl::flat_hash_map<int, int> parant_vector_index;
>   for (int i = 0; i < nodes.size(); ++i) {
>     if (nodes[i].has_branch_node()) {
> ```

Negate this to reduce nesting:

```
if (!nodes[i].has_branch_node()) continue;
// now the rest of the loop body is unindented
```
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Mr4PVyh7kvCZX465wLL:-Mr4PVyh7kvCZX465wLM:b317yi6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/0eafae3815c866156d6d72c7cb2766e260fb9373/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L59)):*
> ```cpp
>                            nodes[i].DebugString()));
>         }
>         parant_vector_index[it->second] = i;
> ```

Typo: `parant` -> `parent`
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Mr4Pe4r6w3M_aUldnzu:-Mr4Pe4r6w3M_aUldnzv:b-x6zmg7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/0eafae3815c866156d6d72c7cb2766e260fb9373/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L70)):*
> ```cpp
>   absl::flat_hash_set<std::string> random_seeds;
>   if (node.has_branch_node()) {
>     const BranchNode& branch_node = node.branch_node();
> ```

Can you pull out some helper functions like `GetRandomSeedsForBranchNode` and `GetRandomSeedForPopulationNode`?
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 106 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Mr4PwwLEMMQk0KrwOxM:-Mr4PwwLEMMQk0KrwOxN:b17xnvp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/0eafae3815c866156d6d72c7cb2766e260fb9373/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L106)):*
> ```cpp
> 
> absl::Status CheckNodeSeeds(const std::vector<CompiledNode>& nodes) {
>   ASSIGN_OR_RETURN(auto parant_vector_index, GetParentIndexMap(nodes));
> ```

Typo: "parent"
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 128 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Mr4QU4Y5KTUD1rhoYWf:-Mr4QU4Y5KTUD1rhoYWg:b5oe235) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/0eafae3815c866156d6d72c7cb2766e260fb9373/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L128)):*
> ```cpp
>       bool has_duplicate = false;
>       for (const std::string& random_seed : random_seeds) {
>         if (ancestor_random_seeds.find(random_seed) !=
> ```

`.contains`?

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @wliue)

___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_names_checker.cc, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Mr4L29C6rnHRo9rkfG6:-MsahaK2BtxHaGmJlDmK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/0eafae3815c866156d6d72c7cb2766e260fb9373/src/main/cc/wfa/virtual_people/training/model_checker/model_names_checker.cc#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Preferred:

```
auto [it, inserted] = names.insert(node.name());
if (!inserted) { return absl::InvalidArgumentError(...); }
```
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Mr4PLnn4L_f0-aZgPzl:-MsahbY2A-1ufbKRxHVq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/0eafae3815c866156d6d72c7cb2766e260fb9373/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Negate this to reduce nesting:

```
if (!nodes[i].has_branch_node()) continue;
// now the rest of the loop body is unindented
```
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Mr4Pe4r6w3M_aUldnzu:-MsahdtQClwIsBmTrQMC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/0eafae3815c866156d6d72c7cb2766e260fb9373/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you pull out some helper functions like `GetRandomSeedsForBranchNode` and `GetRandomSeedForPopulationNode`?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 128 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Mr4QU4Y5KTUD1rhoYWf:-Msahfjt2Me7hGDzficD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/0eafae3815c866156d6d72c7cb2766e260fb9373/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L128)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`.contains`?
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Msajdit29_sxye-vTf-:-MsajdiuC8vAw6nY_gHP:bi82o50) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L110)):*
> ```cpp
>   absl::flat_hash_set<std::string> random_seeds;
>   if (node.has_branch_node()) {
>     GetRandomSeedsForBranchNode(node.branch_node(), random_seeds);
> ```

Please just change these to return a hash set instead of taking one in as a parameter (https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs).

**Review by wliue — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12)* status: all files reviewed, 6 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_checker_main.cc, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Msbnsqr65zr8woyRwQI:-Msbnsqr65zr8woyRwQJ:b-56edd7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_checker_main.cc#L52)):*
> ```cpp
>       wfa::ReadRiegeliFile<wfa_virtual_people::CompiledNode>(model_path, nodes);
>   CHECK(read_status.ok()) << read_status;
> ```

How about also load the model via Labeler::Build()? It also does many checks, and we expect the model file will be used by labeler.
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_names_checker.h, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Msbe3siArT2zU93KPr2:-Msbe3siArT2zU93KPr3:b-a59i75) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_names_checker.h#L27)):*
> ```objc
> // Return error status if there are any duplicated names in @nodes.
> //
> // Any child node should be referenced by index rather than the CompiledNode
> ```

Could clarify that this is an assumption, rather than something checked by this method.



_Code quote:_
```objc
// Any child node should be referenced by index rather than the CompiledNode
// object.
```
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-MsbfikZCijXik_P0YQR:-MsbfikZCijXik_P0YQS:bfo8riw) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L39)):*
> ```cpp
>     if (nodes[i].has_index()) {
>       node_index_to_vector_index[nodes[i].index()] = i;
>     }
> ```

Maybe return error if a node has no index?
If the file represents a valid model, then only the root node may not have an index. I think it is ok to assign index to all nodes in the model compiler.

 
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 121 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-MsbjYZ74SZ5im8UulFi:-MsbjYZ74SZ5im8UulFj:bxcxxh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L121)):*
> ```cpp
>   // To store the indexes of the nodes that has any duplicated random seed.
>   std::vector<int> violation_indexes;
>   for (int i = 0; i < nodes.size(); ++i) {
> ```

While perf is not critical for the model checker tool, how about first compute random seeds for all nodes and store in a map? 



_Code quote:_
```cpp
  for (int i = 0; i < nodes.size(); ++i) {
```
___
*[src/test/cc/wfa/virtual_people/training/model_checker/model_names_checker_test.cc, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-MsbluZ0-tht6Jfr8COI:-MsbluZ0-tht6Jfr8COJ:bmxh4zv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/test/cc/wfa/virtual_people/training/model_checker/model_names_checker_test.cc#L57)):*
> ```cpp
>       )pb",
>       &nodes.emplace_back()));
>   EXPECT_THAT(CheckNodeNames(nodes),
> ```

Nit: maybe add another node with a different name to verify it is not checking that all nodes have the same name?

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12)* status: 6 of 10 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @wliue)

___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_checker_main.cc, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Msbnsqr65zr8woyRwQI:-MscBJyq4BqQ8V0yrY3i:b-y7cw91) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_checker_main.cc#L52)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

How about also load the model via Labeler::Build()? It also does many checks, and we expect the model file will be used by labeler.
</blockquote></details>

I prefer the model builder and the labeler are decoupled, as they may have different version.
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_names_checker.h, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Msbe3siArT2zU93KPr2:-MscHwob00YXD2nTaRhO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_names_checker.h#L27)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could clarify that this is an assumption, rather than something checked by this method.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-MsbfikZCijXik_P0YQR:-MscCi1H5CTSBDSL5Nvu:bau1090) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L39)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Maybe return error if a node has no index?
If the file represents a valid model, then only the root node may not have an index. I think it is ok to assign index to all nodes in the model compiler.

 
</blockquote></details>

Added a TODO. We will do this in future PRs.
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Msajdit29_sxye-vTf-:-MscHz4N2JiHzlICCGTj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L110)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please just change these to return a hash set instead of taking one in as a parameter (https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs).
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 121 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-MsbjYZ74SZ5im8UulFi:-MscI-FL9z5sNPUvzgpB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L121)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

While perf is not critical for the model checker tool, how about first compute random seeds for all nodes and store in a map? 
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12)* status: all files reviewed, 6 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Msajdit29_sxye-vTf-:-MscRU95ETAkPgblUzsL:bj0nspf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L110)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Out of curiosity, why delete `GetRandomSeedForPopulationNode`?
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-MscRFvo3O4rvYOWSjq5:-MscRFvo3O4rvYOWSjq6:b-txy31b) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b947c2a06a7a1f3a81d852c88d6bf5173f8d96ab/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L103)):*
> ```cpp
>   if (node.has_branch_node()) {
>     absl::flat_hash_set<std::string> branch_node_seeds =
>         GetRandomSeedsForBranchNode(node.branch_node());
> ```

Why not just `return GetRandomSeedsForBranchNode(...);`?

**Review by wliue — APPROVED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12)* status: all files reviewed, 6 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 115 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-MscTMMKCrKtvyRrIE0t:-MscTMMKCrKtvyRrIE0u:b-807afv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b947c2a06a7a1f3a81d852c88d6bf5173f8d96ab/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L115)):*
> ```cpp
> 
> // Get the random seeds for all nodes, and store the seeds in the same order as
> // the ndoes.
> ```

Typo.

**Review by tcsnfkx — COMMENTED** [review]
> Dismissed @wliue from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, and @my2457)

___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-Msajdit29_sxye-vTf-:-Mt6myIKBVLo8e1TjJFx:b-hmjdj2) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/5f4f30e29f80f9824b9c48034e3c0586d23d33b6/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L110)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Out of curiosity, why delete `GetRandomSeedForPopulationNode`?
</blockquote></details>

Added back.
___
*[src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc, line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12#-MscRFvo3O4rvYOWSjq5:-Mt6n-eE3MDoFCV9b2yZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b947c2a06a7a1f3a81d852c88d6bf5173f8d96ab/src/main/cc/wfa/virtual_people/training/model_checker/model_seeds_checker.cc#L103)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why not just `return GetRandomSeedsForBranchNode(...);`?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, and @my2457)

**Review by mpatel24 — APPROVED** [review]

**Pull request merged**
