### PR TITLE
Add protos for high level VirtualID model config.

### LINKED ISSUE #13: Create a binary to compile virtual people model

### PR DESCRIPTION
**Pull request by wliue**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/6)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/6)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/proto/wfa/virtual_people/training/activity_density_function.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/6#-Mh56CmM4YJXmW2NZReS:-Mh56CmM4YJXmW2NZReT:b-200w25) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2dc20b3d3eec7ee41ef57da21c72d42b85cde4c0/src/main/proto/wfa/virtual_people/training/activity_density_function.proto#L27)):*
> ```protobuf
> message DiracDelta {
>   // Location of the delta.
>   repeated double ds = 1;
> ```

Is there a more descriptive name that could be used here?
___
*[src/main/proto/wfa/virtual_people/training/BUILD.bazel, line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/6#-Mh56pCs6KsBGy6f3Hhv:-Mh56pCw6dswuaoWVcpL:bvd7hsn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2dc20b3d3eec7ee41ef57da21c72d42b85cde4c0/src/main/proto/wfa/virtual_people/training/BUILD.bazel#L6)):*
> ```Starlark
> package(default_visibility = ["//visibility:public"])
> 
> proto_library(
> ```

Can you strip the src/main/proto prefix?

**Review by mpatel24 — APPROVED** [review]

**Review by tcsnfkx — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/6)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/6)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/proto/wfa/virtual_people/training/activity_density_function.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/6#-Mh56CmM4YJXmW2NZReS:-MhGaCPtCcoF9CK4ETnx:bpojkwv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2dc20b3d3eec7ee41ef57da21c72d42b85cde4c0/src/main/proto/wfa/virtual_people/training/activity_density_function.proto#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is there a more descriptive name that could be used here?
</blockquote></details>

Change to "coordinates".
___
*[src/main/proto/wfa/virtual_people/training/BUILD.bazel, line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/6#-Mh56pCs6KsBGy6f3Hhv:-MhGaKll381R9ahDItbB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2dc20b3d3eec7ee41ef57da21c72d42b85cde4c0/src/main/proto/wfa/virtual_people/training/BUILD.bazel#L6)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you strip the src/main/proto prefix?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, and @oliver-amzn)

**Pull request merged**
