### PR TITLE
Create empty population pool with single pool and population offset and total population being 0

### LINKED ISSUE #21: Make model compiler handle empty population pools correctly.
Currently model compiler may create population node with no pool, which will fail the Labeler. The expected output should be a node with single pool, with both population offset and total population being 0.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23)

### CODE REVIEW

**Review by wangyaopw — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @mpatel24, @stevenwarejones, and @wliue)

**Review by wliue — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @mpatel24, @stevenwarejones, and @tcsnfkx)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 427 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23#-N6tP-kF3Iinb9GeYXVi:-N6tP-kF3Iinb9GeYXVj:bv4zxh0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/eda846725b4a9765449a3d511fd98b601a678f50/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L427)):*
> ```cpp
>       empty_pool->set_population_offset(0);
>       empty_pool->set_total_population(0);
>     }
> ```

is this check still needed that the last delta is empty?



_Code quote:_
```cpp
    if (delta_pools.back().empty()) {
      // Build empty population pool for the case that kappa < 1.
      CompiledNode* last_delta_node =
          identifier_node->mutable_branch_node()
              ->mutable_branches(
                  identifier_node->branch_node().branches_size() - 1)
              ->mutable_node();
      if (last_delta_node->population_node().pools_size() != 0) {
        return absl::InternalError("Last delta should be empty.");
      }
      PopulationNode::VirtualPersonPool* empty_pool =
          last_delta_node->mutable_population_node()->add_pools();
      empty_pool->set_population_offset(0);
      empty_pool->set_total_population(0);




    }
```

**Review by mpatel24 — APPROVED** [review]

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv and @tcsnfkx)

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv and @wliue)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 427 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23#-N6tP-kF3Iinb9GeYXVi:-N6xrDdPEgQJQPGLQRFm:btla89c) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/eda846725b4a9765449a3d511fd98b601a678f50/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L427)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

is this check still needed that the last delta is empty?
</blockquote></details>

This is already covered by the handling of empty delta pools above.

**Review by wliue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv and @tcsnfkx)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 427 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23#-N6tP-kF3Iinb9GeYXVi:-N6xrnH9Dnqg8543tJV5:b-1airt) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/eda846725b4a9765449a3d511fd98b601a678f50/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L427)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

This is already covered by the handling of empty delta pools above.
</blockquote></details>

It sets empty pool if the last one is empty, however, the old code first verifies that the last pool is empty, and the new code will pass if the last pool is not empty. So the question is, is it still expected that the last pool is empty, therefore need a check first?

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv and @wliue)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 427 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23#-N6tP-kF3Iinb9GeYXVi:-N6yKgxdEZSeKzLEMubO:b-csnm6a) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/eda846725b4a9765449a3d511fd98b601a678f50/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L427)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

It sets empty pool if the last one is empty, however, the old code first verifies that the last pool is empty, and the new code will pass if the last pool is not empty. So the question is, is it still expected that the last pool is empty, therefore need a check first?
</blockquote></details>

If the last element of delta_pools is empty, the last population_node will be an empty pool.
Otherwise, the last population_node will not be an empty pool.
So the check is redundant.

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv)

**Pull request merged**
