### PR TITLE
Add support for contextual boolean expression and string list/map spec.

### PR DESCRIPTION
**Pull request by wliue**
These are used for applying comprehension on VID model configuration.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/18)

### CODE REVIEW

**Comment by tcsnfkx** [comment]
*[`src/main/cc/wfa/virtual_people/training/model_compiler/comprehension/spec_util.cc` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/18#-N4hwMs3BDqvJbQWJSWe:-N4hwMs3BDqvJbQWJSWf:b-3syopw) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/6e067482ef4f32ca9dfdfb9dfbaf4fbfc1533470/src/main/cc/wfa/virtual_people/training/model_compiler/comprehension/spec_util.cc#L42)):*
> ```cpp
> namespace {
> 
> absl::StatusOr<std::string> GetFileContent(const std::string& filename) {
> ```

I think it makes sense to have these file and csv reading libraries in common-cpp repo. Maybe add a TODO here.

**Review by wliue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/18)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @mpatel24, @tcsnfkx, and @wangyaopw)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/comprehension/spec_util.cc` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/18#-N4hwMs3BDqvJbQWJSWe:-N4i2cFC67cH5qhAlhDw:bcolaq4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/6e067482ef4f32ca9dfdfb9dfbaf4fbfc1533470/src/main/cc/wfa/virtual_people/training/model_compiler/comprehension/spec_util.cc#L42)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

I think it makes sense to have these file and csv reading libraries in common-cpp repo. Maybe add a TODO here.
</blockquote></details>

Added TODO for GetFileContent(). The rest (CSV related) are specific to comprehension so I think it is better to keep them here.

**Comment by tcsnfkx** [comment]
*[`src/main/cc/wfa/virtual_people/training/model_compiler/comprehension/comprehension_method.h` line 14 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/18#-N4i51W1DTi6xZv2tthw:-N4i51W28hVnx0ydVHWd:b-tglf1k) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/d2dff2d347b2d999db2d3f6df5c74076e9474a91/src/main/cc/wfa/virtual_people/training/model_compiler/comprehension/comprehension_method.h#L14)):*
> ```objc
> // See the License for the specific language governing permissions and
> // limitations under the License.
> ```

Maybe give an example here?

**Review by wliue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/18)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @mpatel24, @tcsnfkx, and @wangyaopw)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/comprehension/comprehension_method.h` line 14 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/18#-N4i51W1DTi6xZv2tthw:-N4iW7bTB_FBK06ZeQh0:blgfhgg) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/d2dff2d347b2d999db2d3f6df5c74076e9474a91/src/main/cc/wfa/virtual_people/training/model_compiler/comprehension/comprehension_method.h#L14)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Maybe give an example here?
</blockquote></details>

Added examples.

**Review by tcsnfkx — APPROVED** [review]
> Reviewed 6 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/18)* status: 3 of 15 files reviewed, 2 unresolved discussions (waiting on @mpatel24, @tcsnfkx, and @wangyaopw)

**Review by tcsnfkx — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 7 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpatel24 and @wangyaopw)

**Review by mpatel24 — APPROVED** [review]

**Review by wangyaopw — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 7 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wliue)

**Pull request merged**
