### PR TITLE
Add specification for conditional assignment in model config.

### LINKED ISSUE #13: Create a binary to compile virtual people model

### PR DESCRIPTION
**Pull request by tcsnfkx**
Update the version of external packages.
Add ignore files for git.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/7)

### CODE REVIEW

**Review by wliue — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @oliver-amzn)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/7)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[.gitignore, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/7#-MiXGu4n47XaLcC0X9Yu:-MiXGu4n47XaLcC0X9Yv:bssetak) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/edc790691f57b1f7f585c1bc538110039dfd452c/.gitignore#L4)):*
> ```ignore
> bazel-out
> bazel-testlogs
> bazel-virtual-people-training
> ```

For consistency with other repos, maybe:

```
# Bazel convenience symlinks.
bazel-*

# Bazel IntelliJ projects.
.ijwb
.clwb

# IntelliJ projects.
.idea/
*.iml
```
___
*[WORKSPACE, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/7#-MiXHBfv5p298VUJl8Zr:-MiXHBfv5p298VUJl8Zs:b7s088e) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/edc790691f57b1f7f585c1bc538110039dfd452c/WORKSPACE#L57)):*
> ```Starlark
> # Virtual-people-common
> http_archive(
>     name = "virtual_people_common",
> ```

Should we switch to versioned releases for this too?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/7)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[.gitignore, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/7#-MiXGu4n47XaLcC0X9Yu:-MiXJ5D16LggbYQ_bE9Z:b-em6pwb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/edc790691f57b1f7f585c1bc538110039dfd452c/.gitignore#L4)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For consistency with other repos, maybe:

```
# Bazel convenience symlinks.
bazel-*

# Bazel IntelliJ projects.
.ijwb
.clwb

# IntelliJ projects.
.idea/
*.iml
```
</blockquote></details>

See also: https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/102

**Review by mpatel24 — APPROVED** [review]

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/7)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

___
*[.gitignore, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/7#-MiXGu4n47XaLcC0X9Yu:-MibK2HRE6PZOZ5WnKQj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/edc790691f57b1f7f585c1bc538110039dfd452c/.gitignore#L4)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

See also: https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/102
</blockquote></details>

Done.
___
*[WORKSPACE, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/7#-MiXHBfv5p298VUJl8Zr:-MibK3MZA4wkFxAjBitI:bw4awcf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/edc790691f57b1f7f585c1bc538110039dfd452c/WORKSPACE#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should we switch to versioned releases for this too?
</blockquote></details>

I think we can do this later when virtual-people-common is ready to release.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, and @oliver-amzn)

**Pull request merged**
