### PR TITLE
Adaptive Dirac Mixture training.

### PR DESCRIPTION
**Pull request by EvgSkv**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: all files reviewed, 7 unresolved discussions (waiting on @AaronRanAn, @EvgSkv, @jiayu-google, @kungfucraig, @lenjoy, @mpatel24, @oliver-amzn, @wliue, and @zasadnyy)

___
*[WORKSPACE, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdU98-1kLDddfpVNQ1:-MfdU98-1kLDddfpVNQ2:bh4537d) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/WORKSPACE#L1)):*
> ```Starlark
> load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
> ```

Can you add this as the first line of WORKSPACE?

`workspace(name = "virtual_people_training")`
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdUuzU4AhsTXg6ADtD:-MfdUuzU4AhsTXg6ADtE:bk4i2ox) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L60)):*
> ```Python
>   """Implements Dirac Mixture."""
> 
>   def __init__(self, alphas, ds):
> ```

Does it make sense to defensively assert on the shape of alphas and ds? Or at least document what they are?
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 69 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdV5J5-F4NRTmDoqQb:-MfdV5J5-F4NRTmDoqQc:b-3j7yw) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L69)):*
> ```Python
>         for alpha, delta in zip(self.alphas, self.ds)))
> 
>   def __call__(self, signal):
> ```

Should `signal` be documented?
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 71 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdUa3b-M91z9sSuGrU:-MfdUa3b-M91z9sSuGrV:b-lhgu4l) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L71)):*
> ```Python
>   def __call__(self, signal):
>     return numpy.hstack(self.alphas).dot(
>         1 - numpy.exp(- self.ds.dot(signal.T)))
> ```

This is the second time you use this exact same subexpression (`1 - exp(-ds.dot(signal.T))`) -- would it make sense to pull out a helper function for it with a meaningful name?
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 134 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdVfaE662y-8yW82fS:-MfdVfaE662y-8yW82fT:b-xpg5e2) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L134)):*
> ```Python
>         new_centers_at_each_step, new_centers_sigma)
>     centers = numpy.vstack([centers, new_centers])
>     alphas = fit_alphas(centers,
> ```

This expression looks like it'll easily fit on one line -- any reason it's split onto 3?
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 144 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdW1Co6vPghh_0RRZN:-MfdW0aU6V5DgFTdcbF5:bf1ptpx) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L144)):*
> ```Python
> 
> 
> class AdaptiveDiracMixture(DiracMixture):
> ```

I feel like this could just be a function rather than a subclass:

```
def dirac_mixture_from_adaptive_fit(...):
  alphas, ds = fit_adaptive_dirac_mixture(...)
  return DiracMixture(alphas, ds)
```

That would also avoid the necessity of pondering what a `DiracMixture(None, None)` means.
___
*[src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdX4aSCpHW0m9bhats:-MfdX4aSCpHW0m9bhatt:b-21w15q) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py#L52)):*
> ```Python
>     prediction = adm(signal)
>     self.assertSequenceAlmostEqual(target, prediction)
>     distance = (target - prediction).dot(target - prediction) ** 0.5
> ```

Would it convey more meaning to use `numpy.linalg.norm`?

**Review by EvgSkv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @AaronRanAn, @efoxepstein, @jiayu-google, @kungfucraig, @lenjoy, @mpatel24, @oliver-amzn, @wliue, and @zasadnyy)

___
*[WORKSPACE, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdU98-1kLDddfpVNQ1:-Mfh2-Gs-Ulaf6VQhmKN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/WORKSPACE#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add this as the first line of WORKSPACE?

`workspace(name = "virtual_people_training")`
</blockquote></details>

Done.
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdUuzU4AhsTXg6ADtD:-Mfh2WssB7x31Pv9RzQW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L60)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Does it make sense to defensively assert on the shape of alphas and ds? Or at least document what they are?
</blockquote></details>

Done.
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 69 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdV5J5-F4NRTmDoqQb:-Mfh2ZDM5Ob_PPx8QZYn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L69)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should `signal` be documented?
</blockquote></details>

Done.
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 71 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdUa3b-M91z9sSuGrU:-Mfh8vPjDPYbqBm0sCmx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is the second time you use this exact same subexpression (`1 - exp(-ds.dot(signal.T))`) -- would it make sense to pull out a helper function for it with a meaningful name?
</blockquote></details>

Done.
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 134 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdVfaE662y-8yW82fS:-Mfh8wUE38S_i1j9iF-9:b4gqsp8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L134)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This expression looks like it'll easily fit on one line -- any reason it's split onto 3?
</blockquote></details>

I wasn't thinking about it when I wrote it.
It does feel right that when the algorithm has two major steps (center sampling, coefficient fitting) both steps take roughly same number of lines.
And generally I find arguments in a column being readable.
If you feel strongly, I'm OK putting them in a line here.
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 144 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdW1Co6vPghh_0RRZN:-Mfh9EwQ7lSfJX8LeWlb:bciwfyr) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L144)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I feel like this could just be a function rather than a subclass:

```
def dirac_mixture_from_adaptive_fit(...):
  alphas, ds = fit_adaptive_dirac_mixture(...)
  return DiracMixture(alphas, ds)
```

That would also avoid the necessity of pondering what a `DiracMixture(None, None)` means.
</blockquote></details>

Separating constructor and initializer of a class seems like a common pattern.
I think both ways of writing it is OK. Let me know if you feel strongly or have further thoughts.
___
*[src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfdX4aSCpHW0m9bhats:-Mfh9b8V-GoexXtqodcX:bb77uf3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/9a2f4863dbc84a7d26576bf9cd39afb54ce895a0/src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Would it convey more meaning to use `numpy.linalg.norm`?
</blockquote></details>

Yes!

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AaronRanAn, @jiayu-google, @kungfucraig, @lenjoy, @mpatel24, @oliver-amzn, @wliue, and @zasadnyy)

**Review by oliver-amzn — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: all files reviewed, 3 unresolved discussions (waiting on @AaronRanAn, @EvgSkv, @jiayu-google, @kungfucraig, @lenjoy, @mpatel24, @wliue, and @zasadnyy)

___
*[WORKSPACE, line 5 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-Mfhqm9J6ZxnyqQuD8C7:-Mfhqm9J6ZxnyqQuD8C8:b-n8xev8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b5a4d8a8e72b1dc88c98641c62ee30808f4b54f7/WORKSPACE#L5)):*
> ```Starlark
> load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
> 
> # Common-cpp
> ```

Why are you pulling in cpp dependencies here, for a Python project? 
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 3 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-Mfhqtzj8UD1yUJSEi-S:-Mfhqtzj8UD1yUJSEi-T:bkf9je0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b5a4d8a8e72b1dc88c98641c62ee30808f4b54f7/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L3)):*
> ```Python
> #!/usr/bin/python
> #
> # Copyright 2021 Google LLC
> ```

Out of curiosity - is that expected that this code is (c) Google and not the Measurement System Owners, like e.g. in the xmm repo ?
___
*[src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-Mfi8EfK9lVUxZl_djfp:-Mfi8EfK9lVUxZl_djfq:b-k4f380) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b5a4d8a8e72b1dc88c98641c62ee30808f4b54f7/src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py#L1)):*
> ```Python
> #!/usr/bin/python
> ```

Can we run these tests via a Github action as part of the PR?

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: all files reviewed, 3 unresolved discussions (waiting on @AaronRanAn, @EvgSkv, @jiayu-google, @kungfucraig, @lenjoy, @mpatel24, @oliver-amzn, @wliue, and @zasadnyy)

___
*[src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-Mfi8EfK9lVUxZl_djfp:-MfiQjC47pUh7rv2HYxq:bnm49vj) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b5a4d8a8e72b1dc88c98641c62ee30808f4b54f7/src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py#L1)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Can we run these tests via a Github action as part of the PR? 
</blockquote></details>

https://github.com/world-federation-of-advertisers/virtual-people-training/pull/2 will add the GitHub actions for testing and linting

**Review by EvgSkv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: all files reviewed, 3 unresolved discussions (waiting on @AaronRanAn, @jiayu-google, @kungfucraig, @lenjoy, @mpatel24, @oliver-amzn, @wliue, and @zasadnyy)

___
*[WORKSPACE, line 5 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-Mfhqm9J6ZxnyqQuD8C7:-MfiLGyD-W-zcHVtQhVS:b-a9lh3v) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b5a4d8a8e72b1dc88c98641c62ee30808f4b54f7/WORKSPACE#L5)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Why are you pulling in cpp dependencies here, for a Python project? 
</blockquote></details>

We need absl and this dependency has it. In the future this repo will have cpp code, so we might include it right away.
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 3 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-Mfhqtzj8UD1yUJSEi-S:-MfiONKJE36AFrvGaKEs:b93v3g4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b5a4d8a8e72b1dc88c98641c62ee30808f4b54f7/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L3)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Out of curiosity - is that expected that this code is (c) Google and not the Measurement System Owners, like e.g. in the xmm repo ?
</blockquote></details>

My mistake. Thanks for pointing this out!
___
*[src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-Mfi8EfK9lVUxZl_djfp:-MfiOEOM4rUe8bWOQIvx:bmjtf7r) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b5a4d8a8e72b1dc88c98641c62ee30808f4b54f7/src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py#L1)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Can we run these tests via a Github action as part of the PR? 
</blockquote></details>

Eli sent PR.

**Review by EvgSkv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: all files reviewed, 3 unresolved discussions (waiting on @AaronRanAn, @jiayu-google, @kungfucraig, @lenjoy, @mpatel24, @oliver-amzn, @wliue, and @zasadnyy)

___
*[src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-Mfi8EfK9lVUxZl_djfp:-MfiRzRa89uKdSL24vLg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b5a4d8a8e72b1dc88c98641c62ee30808f4b54f7/src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py#L1)):*
<details><summary><i>Previously, EvgSkv (Evgeny Skvortsov) wrote…</i></summary><blockquote>

Eli sent PR.
</blockquote></details>

Done.

**Review by oliver-amzn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AaronRanAn, @jiayu-google, @kungfucraig, @lenjoy, @mpatel24, @wliue, and @zasadnyy)

___
*[WORKSPACE, line 5 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-Mfhqm9J6ZxnyqQuD8C7:-MfigvIc3kMl93t5O29V:b44tpx) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b5a4d8a8e72b1dc88c98641c62ee30808f4b54f7/WORKSPACE#L5)):*
<details><summary><i>Previously, EvgSkv (Evgeny Skvortsov) wrote…</i></summary><blockquote>

We need absl and this dependency has it. In the future this repo will have cpp code, so we might include it right away.
</blockquote></details>

👍
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 3 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-Mfhqtzj8UD1yUJSEi-S:-MfigzpB1tlC7-PS0Xnr:b44tpx) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b5a4d8a8e72b1dc88c98641c62ee30808f4b54f7/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L3)):*
<details><summary><i>Previously, EvgSkv (Evgeny Skvortsov) wrote…</i></summary><blockquote>

My mistake. Thanks for pointing this out!
</blockquote></details>

👍
___
*[src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py, line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-Mfi8EfK9lVUxZl_djfp:-Mfih0ip6AsGjHmxQBHz:b-vocrh7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/b5a4d8a8e72b1dc88c98641c62ee30808f4b54f7/src/test/py/wfa/virtual_people/training/adf/dirac_mixture_test.py#L1)):*
<details><summary><i>Previously, EvgSkv (Evgeny Skvortsov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

👍👍

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AaronRanAn, @jiayu-google, @kungfucraig, @lenjoy, @mpatel24, @wliue, and @zasadnyy)

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: all files reviewed, 2 unresolved discussions (waiting on @AaronRanAn, @EvgSkv, @jiayu-google, @kungfucraig, @lenjoy, @mpatel24, and @zasadnyy)

___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 3 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfoJgegA5rZNqxk3-1a:-MfoJgeh6l7fqXMR3A75:b2rpt7r) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/cfb5779293b35910e52a51afe97d381376a2ec6a/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L3)):*
> ```Python
> #!/usr/bin/python
> #
> # Copyright 2021 The Cross-Media Measurement Authors 
> ```

This shows a red dot at the end, maybe a trailing space?
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 96 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfoKrEO1y2N4uzd5Cnp:-MfoKrEO1y2N4uzd5Cnq:bhndi7x) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/cfb5779293b35910e52a51afe97d381376a2ec6a/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L96)):*
> ```Python
>     coordinate is reach of i-th audience.
>     For given signal location of Dirac Deltas all Dirac Mixtures form
>     a linear cone. This functions returns basis of the cone.
> ```

functions -> function

**Review by EvgSkv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @AaronRanAn, @efoxepstein, @jiayu-google, @lenjoy, @mpatel24, @wliue, and @zasadnyy)

___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 3 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfoJgegA5rZNqxk3-1a:-MgohNzT0tRncUbGnGJY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/cfb5779293b35910e52a51afe97d381376a2ec6a/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L3)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

This shows a red dot at the end, maybe a trailing space?
</blockquote></details>

Done.
___
*[src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py, line 96 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1#-MfoKrEO1y2N4uzd5Cnp:-MgohMpp4PRtakwTgtPb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/cfb5779293b35910e52a51afe97d381376a2ec6a/src/main/py/wfa/virtual_people/training/adf/dirac_mixture.py#L96)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

functions -> function
</blockquote></details>

Done.

**Review by wliue — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 1 of 3 files at r3, 1 of 2 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AaronRanAn, @jiayu-google, @lenjoy, @mpatel24, and @zasadnyy)

**Pull request merged**
