### PR TITLE
Add a sentence describing repo.

### PR DESCRIPTION
**Pull request by EvgSkv**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/5)

### CODE REVIEW

**Review by wliue — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/5)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/5#-MgrYR5v9UmxNr2qTgQx:-MgrYR5w7RObIycOg40P:b-j4lvrd) (no related file):*
Supernit: "sentense" -> "sentence" in PR title

---

**Review by EvgSkv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/5)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/5#-MgrYR5v9UmxNr2qTgQx:-Mgrlx6i01iyQTOIJRYl:bexblga) (no related file):*
> sentence
Will change in the final merge. The initial title appears to be read-only.

---

**Review by EvgSkv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/5)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/5#-MgrYR5v9UmxNr2qTgQx:-Mgrn4my-iPuWHfKc1yl:b-896fix) (no related file):*
<details><summary><i>Previously, EvgSkv (Evgeny Skvortsov) wrote…</i></summary><blockquote>

> sentence
Will change in the final merge. The initial title appears to be read-only.

</blockquote></details>

Done.

---

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv)

**Pull request merged**
