### PR TITLE
Create cookie monster pool instead of empty pool to handle kappa < 1.

### LINKED ISSUE #27: determine population pool for kappa < 1 and update model compiler
There is an ongoing discussion regarding population pool for kappa < 1.
Currently a pool with {offset = 0, total = 0} is used for this.
Need to update model compiler once it is finalized.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @EvgSkv, @mpatel24, @stevenwarejones, @tcsnfkx, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NFLA1DLEVwcfb9GkEXr:-NFLA1DM6ccohpQteg5w:bl2dmmj) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2be0d1327833ac7f206a91d3cbca11de2fe7d98b/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L168)):*
> ```cpp
>         kCookieMonsterOffset) {
>       return absl::InvalidArgumentError(absl::StrCat(
>           "The record overlaps with reserved id range: ",
> ```

nit: also add kCookieMonsterOffset to the log?



_Code quote:_
```cpp
kCookieMonsterOffset
```
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 447 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NFLBkgv-fwVm0Oag9bs:-NFLBkgv-fwVm0Oag9bt:b-wau980) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2be0d1327833ac7f206a91d3cbca11de2fe7d98b/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L447)):*
> ```cpp
>       CompiledNode* empty_pool_node = empty_pool_branch->mutable_node();
>       empty_pool_node->set_name(
>           absl::StrCat(identifier_node->name(), "_empty_pool"));
> ```

do you want to rename the node with a new postfix?



_Code quote:_
```cpp
_empty_pool
```
___
*[`src/test/cc/wfa/virtual_people/training/model_compiler/test_data/compiled_node_for_population_node_redistribute_probabilities_for_cookie_monster_pool.textproto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NFLBVdD4fvaiJw_cWzI:-NFLBVdD4fvaiJw_cWzJ:bglnsfp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2be0d1327833ac7f206a91d3cbca11de2fe7d98b/src/test/cc/wfa/virtual_people/training/model_compiler/test_data/compiled_node_for_population_node_redistribute_probabilities_for_cookie_monster_pool.textproto#L33)):*
> ```
>                           branches {
>                             node {
>                               name: "node1_country_COUNTRY_CODE_1_region_REGION_CODE_1_pool_MULTIPOOL_RECORD_1_identifier_type_IDENTIFIER_TYPE_1_delta_1"
> ```

why is this cookie monster node named `delta_1`?



_Code quote:_
```
1_delta_1
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: all files reviewed, 3 unresolved discussions (waiting on @EvgSkv, @mpatel24, @tcsnfkx, and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: all files reviewed, 5 unresolved discussions (waiting on @EvgSkv, @mpatel24, and @tcsnfkx)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 162 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NFQgWlY4IJahtvTaEDs:-NFQgWlY4IJahtvTaEDt:bx7euax) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2be0d1327833ac7f206a91d3cbca11de2fe7d98b/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L162)):*
> ```cpp
> 
> // Returns error if the pool of any record overlaps with reserved id range which
> // is >= kCookieMonsterOffset.
> ```

Nit: Maybe use its own variable. Cookie monster is just one type of reserved id range, happen to be at the beginning.



_Code quote:_
```cpp
// is >= kCookieMonsterOffset.
```
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/constants.h` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NFQfXK917O7GeWariLd:-NFQfXK917O7GeWariLe:b-khirdr) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2be0d1327833ac7f206a91d3cbca11de2fe7d98b/src/main/cc/wfa/virtual_people/training/model_compiler/constants.h#L25)):*
> ```objc
> 
> // The offset and size of the cookie monster pool.
> constexpr uint64_t kCookieMonsterOffset = 1000000000000000000;
> ```

Add comment and/or ruler that these are 10^18 and 10^14.
Could also mention here that id range starting from kCookieMonsterOffset is reserved, or better, add a constant for start of reserved space.



_Code quote:_
```objc
constexpr uint64_t kCookieMonsterOffset = 1000000000000000000;
constexpr uint64_t kCookieMonsterSize = 100000000000000;
```

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @EvgSkv, @mpatel24, @stevenwarejones, @wangyaopw, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 447 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NFLBkgv-fwVm0Oag9bs:-NFQu7ng0v76PCkbVSjH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2be0d1327833ac7f206a91d3cbca11de2fe7d98b/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L447)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

do you want to rename the node with a new postfix?
</blockquote></details>

Done.
___
*[`src/test/cc/wfa/virtual_people/training/model_compiler/test_data/compiled_node_for_population_node_redistribute_probabilities_for_cookie_monster_pool.textproto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NFLBVdD4fvaiJw_cWzI:-NFQuArpCBtdicufh2Wk:bsbwqgk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2be0d1327833ac7f206a91d3cbca11de2fe7d98b/src/test/cc/wfa/virtual_people/training/model_compiler/test_data/compiled_node_for_population_node_redistribute_probabilities_for_cookie_monster_pool.textproto#L33)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

why is this cookie monster node named `delta_1`?
</blockquote></details>

This was created due to discretization. Fixed to remove the empty delta pools from the model as they have zero probabilities.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @mpatel24, @stevenwarejones, @tcsnfkx, and @wliue)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @mpatel24, and @tcsnfkx)

**Review by tcsnfkx — COMMENTED** [review]
> Dismissed @wliue from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @EvgSkv, @mpatel24, @stevenwarejones, @wangyaopw, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 162 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NFQgWlY4IJahtvTaEDs:-NFoNNzY4iGifZ46DVcw:b-4bkivc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2be0d1327833ac7f206a91d3cbca11de2fe7d98b/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L162)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Nit: Maybe use its own variable. Cookie monster is just one type of reserved id range, happen to be at the beginning.
</blockquote></details>

We can update this range when we have more reserved id range in future. Currently ">= kCookieMonsterOffset" is the only reserved id range.
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/constants.h` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NFQfXK917O7GeWariLd:-NFoObpr2f7hQwF9RROY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/2be0d1327833ac7f206a91d3cbca11de2fe7d98b/src/main/cc/wfa/virtual_people/training/model_compiler/constants.h#L25)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Add comment and/or ruler that these are 10^18 and 10^14.
Could also mention here that id range starting from kCookieMonsterOffset is reserved, or better, add a constant for start of reserved space.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv and @mpatel24)

**Review by wliue — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @mpatel24, and @tcsnfkx)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 168 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NGIrjug7ke6uu_3wGGI:-NGIrjug7ke6uu_3wGGJ:bn3eacb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/f3ede6a92061dc9301bf5d8805b486142e31ac59/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L168)):*
> ```cpp
>         kCookieMonsterOffset) {
>       return absl::InvalidArgumentError(
>           absl::StrCat("The record contains ids >= kCookieMonsterOffset: ",
> ```

Could also write the value of kCookieMonsterOffset.
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/constants.h` line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NGIqCvw8sMQJqsDWpBs:-NGIqCvw8sMQJqsDWpBt:b-ffiq9o) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/f3ede6a92061dc9301bf5d8805b486142e31ac59/src/main/cc/wfa/virtual_people/training/model_compiler/constants.h#L26)):*
> ```objc
> // The offset and size of the cookie monster pools.
> // ID range starting from kCookieMonsterOffset, including those >=
> // kCookieMonsterSize, is reserved.
> ```

This should be kCookieMonsterOffset + kCookieMonsterSize, or change to "above cookie monster range".



_Code quote:_
```objc
// ID range starting from kCookieMonsterOffset, including those >=
// kCookieMonsterSize, is reserved.
```

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @mpatel24, @stevenwarejones, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 168 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NGIrjug7ke6uu_3wGGI:-NGNb6Xb7VTtmMH_zakI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/f3ede6a92061dc9301bf5d8805b486142e31ac59/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L168)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could also write the value of kCookieMonsterOffset.
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/constants.h` line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29#-NGIqCvw8sMQJqsDWpBs:-NGNb9-X4oDxK4sGT7GI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/f3ede6a92061dc9301bf5d8805b486142e31ac59/src/main/cc/wfa/virtual_people/training/model_compiler/constants.h#L26)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

This should be kCookieMonsterOffset + kCookieMonsterSize, or change to "above cookie monster range".
</blockquote></details>

Done.

**Review by tcsnfkx — COMMENTED** [review]
> Dismissed @wliue from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @EvgSkv, @mpatel24, @stevenwarejones, and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv and @mpatel24)

**Pull request merged**
