### PR TITLE
Allow the kappa to be less than 1.

### LINKED ISSUE #25: handle kappa < 1 case in model compiler
Currently the model compiler checks that kappa = 1 in the high-level model config. The expectation is that there is a small alpha and corresponding delta that account for (1 - kappa).
Need to update model compiler to handle this automatically.

### PR DESCRIPTION
**Pull request by tcsnfkx**
Empty population pool is created for the case with kappa less than 1.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26)

### CODE REVIEW

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @mpatel24, @stevenwarejones, @tcsnfkx, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 407 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9lcUaG0jzCqtWVig2T:-N9lcUaG0jzCqtWVig2U:b-hc3ecu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L407)):*
> ```cpp
>       return absl::InvalidArgumentError("Kappa is larger than 1.");
>     } else if (kappa < 1.0 - kKappaAllowedError) {
>       need_empty_pool = true;
> ```

Have we decided whether to not assign VID for (1-kappa) or assign a constant VID?

Maybe add a comment explaining what the empty pool is used for here



_Code quote:_
```cpp
 need_empty_pool = true;
```
___
*[`src/test/cc/wfa/virtual_people/training/model_compiler/test_data/compiled_node_for_population_node_kappa_less_than_one.textproto` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9laMqq8mzUvcvK8-ZJ:-N9laMqq8mzUvcvK8-ZK:barmysj) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/test/cc/wfa/virtual_people/training/model_compiler/test_data/compiled_node_for_population_node_kappa_less_than_one.textproto#L22)):*
> ```
>                             node {
>                               name: "node1_country_COUNTRY_CODE_1_region_REGION_CODE_1_pool_MULTIPOOL_RECORD_1_identifier_type_IDENTIFIER_TYPE_1_empty_pool"
>                               population_node {
> ```

Isn't the empty node appended to the end of the list?



_Code quote:_
```
                            node {
                              name: "node1_country_COUNTRY_CODE_1_region_REGION_CODE_1_pool_MULTIPOOL_RECORD_1_identifier_type_IDENTIFIER_TYPE_1_empty_pool"
                              population_node {
                                pools {
                                  population_offset: 0
                                  total_population: 0
                                }
                              }
                            }
                            chance: 0.5
```

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @EvgSkv, @mpatel24, @stevenwarejones, @tcsnfkx, and @wangyaopw)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 342 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9m5Wrr4ZLyGBbzRzaD:-N9m5WrsAahVwM8Db8YW:bidxida) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L342)):*
> ```cpp
>   std::vector<int> non_empty_indexes;
>   for (int i = 0; i < delta_pool_sizes.size(); ++i) {
>     if (delta_pool_sizes[i] > 0) {
> ```

We now add pool offset=0/total=0 to represent empty pool. Is this check still correct? Please add a unittest for this case.



_Code quote:_
```cpp
  for (int i = 0; i < delta_pool_sizes.size(); ++i) {
    if (delta_pool_sizes[i] > 0) {
      non_empty_indexes.push_back(i);
    }
  }
```
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 347 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9misjU31OoGDCfhnai:-N9misjU31OoGDCfhnaj:by55bhp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/f518b360514e60ba696d58368a19784731a34f6a/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L347)):*
> ```cpp
> 
>   std::vector<double> output(original_probabilities.size(), 0.0);
>   output[original_probabilities.size() - 1] =
> ```

Was there an assumption that the last alpha/delta is to handle kappa < 1? There is not necessarily such an alpha, and it is not guaranteed to be the last one. Please double check whether the current code still use this assumption. 



_Code quote:_
```cpp
  output[original_probabilities.size() - 1] =
      original_probabilities[original_probabilities.size() - 1];
```
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 405 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9mkHCEEC19ImVer_cs:-N9mkHCEEC19ImVer_ct:b-90xy30) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L405)):*
> ```cpp
>     bool need_empty_pool = false;
>     if (kappa > 1.0 + kKappaAllowedError) {
>       return absl::InvalidArgumentError("Kappa is larger than 1.");
> ```

Could also log kappa.
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 407 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9lcUaG0jzCqtWVig2T:-N9mkN9H0ORPEZx9hPCI:b-npbhav) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L407)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Have we decided whether to not assign VID for (1-kappa) or assign a constant VID?

Maybe add a comment explaining what the empty pool is used for here
</blockquote></details>

The current proposal is to use a very large special pool (e.g. VID range above normal VID range) for this. It is still under discussion.
Maybe change need_empty_pool to need_extra_pool, and add comment. Might still be OK to call it "empty" though because it has no real people.
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 443 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9mlXBODp0op33pSqu2:-N9mlXBODp0op33pSqu3:b-3abhvi) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L443)):*
> ```cpp
>       delta_node->set_name(absl::StrCat(identifier_node->name(), "_delta_", j));
>       if (delta_pools[j].empty()) {
>         AddEmptyPoolForNode(*delta_node);
> ```

Somehow we need to differentiate a normal pool with total=0(due to small alpha), and the pool to handle (1 - kappa). We need to ensure the probability is 0 in the former case, or remove such pools. We can revisit this after the decision is finalized for how to represent empty pool.



_Code quote:_
```cpp
        AddEmptyPoolForNode(*delta_node);
```
___
*[`src/test/cc/wfa/virtual_people/training/model_compiler/test_data/compiled_node_for_population_node_kappa_less_than_one.textproto` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9laMqq8mzUvcvK8-ZJ:-N9mnAYY88GU8kQDBjCN:bixsqvr) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/test/cc/wfa/virtual_people/training/model_compiler/test_data/compiled_node_for_population_node_kappa_less_than_one.textproto#L22)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Isn't the empty node appended to the end of the list?
</blockquote></details>

Current code adds the empty node first. From labeling point of view the order doesn't matter. I have no strong opinion where to put it but we need to be consistent. 
___
*[`src/test/cc/wfa/virtual_people/training/model_compiler/test_data/model_node_config_population_node_kappa_less_than_one.textproto` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9mox-H5BNkpR155aRO:-N9mox-H5BNkpR155aRP:bmqcvbc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/test/cc/wfa/virtual_people/training/model_compiler/test_data/model_node_config_population_node_kappa_less_than_one.textproto#L23)):*
> ```
>   adf {
>     verbatim {
>       name: "ADF_1"
> ```

Is this test intended for failure case kappa < 1? What is the error with the original config?

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @EvgSkv, @mpatel24, @stevenwarejones, @wangyaopw, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 342 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9m5Wrr4ZLyGBbzRzaD:-NAMW_VL4INReAUwT77j:bw8z3yi) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L342)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

We now add pool offset=0/total=0 to represent empty pool. Is this check still correct? Please add a unittest for this case.
</blockquote></details>

This is still correct. We make the probability to be 0 for the delta pools with size 0. We have delta pools with size 0 because of discretization, rather than creating empty pools intentionally. We already have tests for discretization.
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 347 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9misjU31OoGDCfhnai:-NAMYCPi1bL6f8WT-B4w:b-7fgrjk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/f518b360514e60ba696d58368a19784731a34f6a/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L347)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Was there an assumption that the last alpha/delta is to handle kappa < 1? There is not necessarily such an alpha, and it is not guaranteed to be the last one. Please double check whether the current code still use this assumption. 
</blockquote></details>

That was the previous assumption. We do not have that assumption now.
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 405 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9mkHCEEC19ImVer_cs:-NAMbpjyBgW0vwuz23VO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L405)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could also log kappa.
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 407 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9lcUaG0jzCqtWVig2T:-NAMbCOLAdyx88gsBrCD:b2gotnc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L407)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

The current proposal is to use a very large special pool (e.g. VID range above normal VID range) for this. It is still under discussion.
Maybe change need_empty_pool to need_extra_pool, and add comment. Might still be OK to call it "empty" though because it has no real people.
</blockquote></details>

I would suggest we keep it as an empty pool for now based on previous decision. We can change it after we decide to use a special pool.
___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 443 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9mlXBODp0op33pSqu2:-NAM_JnT172Xw_wp0oPK:b-ybnpdc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L443)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Somehow we need to differentiate a normal pool with total=0(due to small alpha), and the pool to handle (1 - kappa). We need to ensure the probability is 0 in the former case, or remove such pools. We can revisit this after the decision is finalized for how to represent empty pool.
</blockquote></details>

This is already handled in RedistributeProbabilitiesByDeltaPoolSizes.
___
*[`src/test/cc/wfa/virtual_people/training/model_compiler/test_data/compiled_node_for_population_node_kappa_less_than_one.textproto` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9laMqq8mzUvcvK8-ZJ:-NAM_WofEqvvQKUe3gr-:b-mzi4ej) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/test/cc/wfa/virtual_people/training/model_compiler/test_data/compiled_node_for_population_node_kappa_less_than_one.textproto#L22)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Current code adds the empty node first. From labeling point of view the order doesn't matter. I have no strong opinion where to put it but we need to be consistent. 
</blockquote></details>

I do not have preference between appending at the beginning or at the end. Maybe appending at the beginning makes it more obvious that the kappa is less than 1.
___
*[`src/test/cc/wfa/virtual_people/training/model_compiler/test_data/model_node_config_population_node_kappa_less_than_one.textproto` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9mox-H5BNkpR155aRO:-NAMap3i6OMKar7jWxPF:b-4n7a86) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/test/cc/wfa/virtual_people/training/model_compiler/test_data/model_node_config_population_node_kappa_less_than_one.textproto#L23)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Is this test intended for failure case kappa < 1? What is the error with the original config?
</blockquote></details>

I think this was intended to test the assumption that the last alpha is to handle kappa < 1, but seems the original test does not handle that correctly.

**Review by tcsnfkx — COMMENTED** [review]
> Dismissed @wangyaopw and @wliue from 7 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @EvgSkv, @mpatel24, @stevenwarejones, and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @mpatel24, and @stevenwarejones)

___
*[`src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc` line 407 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-training/26#-N9lcUaG0jzCqtWVig2T:-NApLxpxEtw-PUBi2bI0:blifo8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/221d6ed2910a3fb372e75b4640ff1c706df6eb23/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc#L407)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

I would suggest we keep it as an empty pool for now based on previous decision. We can change it after we decide to use a special pool.
</blockquote></details>

Agree to keep it as empty pool for now.

**Review by mpatel24 — APPROVED** [review]

**Pull request merged**
